# This is a basic workflow to help you get started with Actions

name: Deploy Application

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  create-deployment-artifacts:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: Compile laravel
        run: |
          npm install
          npm run prod

      - name: Configure PHP 7.4
        uses: shivammathur/setup-php@master
          with:
            php-version: 7.4
            extensions: mbstring, ctype, fileinfo, openssl, PDO, bcmath, json, tokenizer, xml

